### PR TITLE
US-157: Edit uwtools documentation

### PR DESCRIPTION
**Pull request by gspetro-NOAA**
**Synopsis**

Minor edits for grammar, formatting, etc. 

**Type**

- [ ] Bug fix (corrects a known issue)
- [ ] Code maintenance (refactoring, etc. without behavior change)
- [X] Documentation
- [ ] Enhancement (adds a new functionality)
- [ ] Tooling (CI, code-quality, packaging, revision-control, etc.)

**Impact**

- [X] This is a non-breaking change (existing functionality continues to work as expected)
- [ ] This is a breaking change (changes existing functionality)

**Checklist**

- [X] I have added myself and any co-authors to the PR's _Assignees_ list.
- [X] I have reviewed the documentation and have made any updates necessitated by this change.

### CODE REVIEW

**Review by maddenp-noaa — APPROVED** [review]
Very helpful, thank you!

**Comment by maddenp-noaa** [comment]
@gspetro-NOAA If you're at a point where you're happy with this and need any help with the merge, I'm happy to help. But feel free to proceed whenever you're ready.

**Comment by gspetro-NOAA** [comment]
@maddenp-noaa , I ran `make docs`, and it comes up with this error: 
```
(           index: line   70)
Warning, treated as error:
/Users/gillianpetro/uwtools/docs/index.rst:70:broken link: https://www.noaa.gov/ (403 Client Error: Forbidden for url: https://www.noaa.gov/)
make[1]: *** [Makefile:20: linkcheck] Error 2
make[1]: Leaving directory '/Users/gillianpetro/uwtools/docs'
make: *** [Makefile:16: docs] Error 2
```
However, the "NOAA" link in the local html rendering of my docs and the ["NOAA" link in the RTD docs](https://gsp-workflow-tools.readthedocs.io/en/text-us-157/index.html) from my fork both work, and the link works separately in my browser. Any idea what might be causing this error?

**Comment by maddenp-noaa** [comment]
Interesting. `curl` also sees an error:
```
% curl https://www.noaa.gov/
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: X3HkWSR4UzQxKI20Ac0GENDz4gRJKlX37HP4XnVe9KxlKdcBx1xJ9g==
</PRE>
<ADDRESS>
</ADDRESS>
```
I'll try to find out why.

**Comment by maddenp-noaa** [comment]
I wonder if it could be related to this: https://stackoverflow.com/questions/32641072/current-observation-feed-from-weather-gov-forbidden-403.

If I `curl -A "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" https://www.noaa.gov/`, that works.

Let me see if there seems to be a way to have Sphinx `linkcheck` use a customer user-agent string.

**Comment by maddenp-noaa** [comment]
Please try adding
```
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
```
to `docs/conf.py` in the block of variables before `extlinks`. Seems to work for me.

**Pull request merged**
